export const UPLOAD_PHOTO = "UPLOAD_PHOTO";
export const UPLOAD_PHOTO_SUCCESS = "UPLOAD_PHOTO_SUCCESS";
export const UPLOAD_PHOTO_ERROR = "UPLOAD_PHOTO_ERROR";

export const RESET_VALUES = "RESET_VALUES";
